Use this notebook to run code to generate rankings and added rankings up through time

In [2]:
import pandas as pd

In [12]:
csv_path = "E:/!!Research/!!!Data/graph_analysis/igraph_metrics_data/lek_rolling_binary_node_metrics.csv"
df = pd.read_csv(csv_path)
df.head()

,Unnamed: 0,lek,x_easting,y_northing,graph_type,year,hub_score,centrality_score
0,0,4624,608585,3702344,average_dispersal,1971,0.740027,0.153846
1,1,4625,609605,3707214,average_dispersal,1971,1.000000,5.800932
2,2,4626,610855,3710424,average_dispersal,1971,1.000000,5.800932
3,3,4627,612215,3712342,average_dispersal,1971,1.000000,5.800932
4,4,4628,612780,3702469,average_dispersal,1971,0.833275,1.399301

Finding hubs

Average dispersal hubs

In [13]:
df_ad = df[df['graph_type'] == 'average_dispersal']


# Define threshold for identifying hubs
threshold = 0.9

# Step 1: Add a column indicating if the lek is a hub for each year
df_ad['is_hub'] = df_ad['hub_score'] >= threshold

# Step 2: Count how many times each lek has been a hub
hub_counts_ad = df_ad.groupby(['lek', 'x_easting', 'y_northing'])['is_hub'].sum().reset_index()

# Rename the columns for clarity
hub_counts_ad.columns = ['lek', 'x_easting', 'y_northing', 'hub_count']

# Step 3: Save to CSV
hub_counts_ad.to_csv('E:/!!Research/!!!Data/graph_analysis/igraph_metrics_data/lek_hub_counts_average_dispersal.csv', index=False)

hub_counts_ad.tail()

C:\Users\Justin-Laptop\AppData\Local\Temp\ipykernel_14008\2471839242.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_ad['is_hub'] = df_ad['hub_score'] >= threshold

       lek  x_easting  y_northing  hub_count
548  64365     599220     3675932          0
549  66666     650336     3722341          8
550  77777     651984     3722855          8
551  88888     652426     3718903          7
552  99999     649863     3714293          0

Round trip hubs

In [14]:
df_rt = df[df['graph_type'] == 'round_trip']


# Define threshold for identifying hubs
threshold = 0.9

# Step 1: Add a column indicating if the lek is a hub for each year
df_rt['is_hub'] = df_rt['hub_score'] >= threshold

# Step 2: Count how many times each lek has been a hub
hub_counts_rt = df_rt.groupby(['lek', 'x_easting', 'y_northing'])['is_hub'].sum().reset_index()

# Rename the columns for clarity
hub_counts_rt.columns = ['lek', 'x_easting', 'y_northing', 'hub_count']

# Step 3: Save to CSV
hub_counts_rt.to_csv('E:/!!Research/!!!Data/graph_analysis/igraph_metrics_data/lek_hub_counts_round_trip.csv', index=False)

hub_counts_rt.tail()

C:\Users\Justin-Laptop\AppData\Local\Temp\ipykernel_14008\3266478744.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_rt['is_hub'] = df_rt['hub_score'] >= threshold

       lek  x_easting  y_northing  hub_count
548  64365     599220     3675932          0
549  66666     650336     3722341         10
550  77777     651984     3722855          9
551  88888     652426     3718903          0
552  99999     649863     3714293          0

Average dispersal hubs

In [15]:
df_md = df[df['graph_type'] == 'max_disperse']


# Define threshold for identifying hubs
threshold = 0.9

# Step 1: Add a column indicating if the lek is a hub for each year
df_md['is_hub'] = df_md['hub_score'] >= threshold

# Step 2: Count how many times each lek has been a hub
hub_counts_md = df_md.groupby(['lek', 'x_easting', 'y_northing'])['is_hub'].sum().reset_index()

# Rename the columns for clarity
hub_counts_md.columns = ['lek', 'x_easting', 'y_northing', 'hub_count']

# Step 3: Save to CSV
hub_counts_md.to_csv('E:/!!Research/!!!Data/graph_analysis/igraph_metrics_data/lek_hub_counts_max_dispersal.csv', index=False)

hub_counts_md.tail()

C:\Users\Justin-Laptop\AppData\Local\Temp\ipykernel_14008\4219282507.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_md['is_hub'] = df_md['hub_score'] >= threshold

       lek  x_easting  y_northing  hub_count
548  64365     599220     3675932          0
549  66666     650336     3722341         10
550  77777     651984     3722855          9
551  88888     652426     3718903          7
552  99999     649863     3714293          8

Home range (4800) hubs

In [16]:
df_hr = df[df['graph_type'] == '48']


# Define threshold for identifying hubs
threshold = 0.9

# Step 1: Add a column indicating if the lek is a hub for each year
df_hr['is_hub'] = df_hr['hub_score'] >= threshold

# Step 2: Count how many times each lek has been a hub
hub_counts_hr = df_hr.groupby(['lek', 'x_easting', 'y_northing'])['is_hub'].sum().reset_index()

# Rename the columns for clarity
hub_counts_hr.columns = ['lek', 'x_easting', 'y_northing', 'hub_count']

# Step 3: Save to CSV
hub_counts_hr.to_csv('E:/!!Research/!!!Data/graph_analysis/igraph_metrics_data/lek_hub_counts_home_range.csv', index=False)

hub_counts_hr.tail()

C:\Users\Justin-Laptop\AppData\Local\Temp\ipykernel_14008\1851472851.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_hr['is_hub'] = df_hr['hub_score'] >= threshold

       lek  x_easting  y_northing  hub_count
548  64365     599220     3675932          0
549  66666     650336     3722341          0
550  77777     651984     3722855          0
551  88888     652426     3718903          0
552  99999     649863     3714293          0

Coalescence hubs

In [17]:
df_co = df[df['graph_type'] == 'coalescence']


# Define threshold for identifying hubs
threshold = 0.9

# Step 1: Add a column indicating if the lek is a hub for each year
df_co['is_hub'] = df_co['hub_score'] >= threshold

# Step 2: Count how many times each lek has been a hub
hub_counts_co = df_co.groupby(['lek', 'x_easting', 'y_northing'])['is_hub'].sum().reset_index()

# Rename the columns for clarity
hub_counts_co.columns = ['lek', 'x_easting', 'y_northing', 'hub_count']

# Step 3: Save to CSV
hub_counts_co.to_csv('E:/!!Research/!!!Data/graph_analysis/igraph_metrics_data/lek_hub_counts_coalescence.csv', index=False)

hub_counts_co.tail()

C:\Users\Justin-Laptop\AppData\Local\Temp\ipykernel_14008\1772126698.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_co['is_hub'] = df_co['hub_score'] >= threshold

       lek  x_easting  y_northing  hub_count
548  64365     599220     3675932          2
549  66666     650336     3722341          8
550  77777     651984     3722855          6
551  88888     652426     3718903          5
552  99999     649863     3714293          6

Testing normalization by count

In [18]:
df_ad_n = df[df['graph_type'] == 'average_dispersal']


# Define threshold for identifying hubs
threshold = 0.9

# Step 1: Add a column indicating if the lek is a hub for each year
df_ad_n['is_hub'] = df_ad_n['hub_score'] >= threshold

# Step 2: Count how many times each lek has been a hub and the number of active years (rows per lek)
hub_counts_ad_n = df_ad_n.groupby(['lek', 'x_easting', 'y_northing']).agg(
    hub_count=('is_hub', 'sum'),
    active_years=('hub_score', 'count')  # Counts each row, indicating active years
).reset_index()


# Step 3: Save to CSV
hub_counts_ad_n.to_csv('E:/!!Research/!!!Data/graph_analysis/igraph_metrics_data/lek_hub_counts_average_dispersal_normal.csv', index=False)

hub_counts_ad_n.tail()

C:\Users\Justin-Laptop\AppData\Local\Temp\ipykernel_14008\2681647268.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_ad_n['is_hub'] = df_ad_n['hub_score'] >= threshold

       lek  x_easting  y_northing  hub_count  active_years
548  64365     599220     3675932          0             6
549  66666     650336     3722341          8            10
550  77777     651984     3722855          8             9
551  88888     652426     3718903          7             7
552  99999     649863     3714293          0             8

### Starting with betweenness centrality

Average dispersal

In [20]:
df_bc_ad = df[df['graph_type'] == 'average_dispersal']


# Define threshold for identifying hubs
threshold = 0.9

# Calculate the 90th quantile of betweenness_centrality across all data
quantile_90 = df_bc_ad['centrality_score'].quantile(0.9)

# Step 1: Add a column indicating if the lek is a hub for each year and if it exceeds the 90th quantile
df_bc_ad['is_stepping_stone'] = df_bc_ad['centrality_score'] >= threshold
df_bc_ad['above_90th_quantile'] = df_bc_ad['centrality_score'] > quantile_90

# Step 2: Count how many times each lek has been a hub, the number of active years, and exceedances of the 90th quantile
hub_counts_bc_ad = df_bc_ad.groupby(['lek', 'x_easting', 'y_northing']).agg(
    hub_count=('is_stepping_stone', 'sum'),
    active_years=('centrality_score', 'count'),  # Counts active years
    above_90th_count=('above_90th_quantile', 'sum')  # Counts years above the 90th quantile
).reset_index()


# Step 3: Save to CSV
hub_counts_bc_ad.to_csv('E:/!!Research/!!!Data/graph_analysis/igraph_metrics_data/lek_step_stone_counts_average_dispersal.csv', index=False)

hub_counts_bc_ad.tail()

C:\Users\Justin-Laptop\AppData\Local\Temp\ipykernel_14008\1634860453.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_bc_ad['is_stepping_stone'] = df_bc_ad['centrality_score'] >= threshold
C:\Users\Justin-Laptop\AppData\Local\Temp\ipykernel_14008\1634860453.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_bc_ad['above_90th_quantile'] = df_bc_ad['centrality_score'] > quantile_90

       lek  x_easting  y_northing  hub_count  active_years  above_90th_count
548  64365     599220     3675932          6             6                 0
549  66666     650336     3722341         10            10                 0
550  77777     651984     3722855          9             9                 0
551  88888     652426     3718903          7             7                 0
552  99999     649863     3714293          8             8                 0